#!/usr/bin/env bash
# Basic restart script

# Restart raspberry pi
sshpass -p raspberry ssh pi@192.168.88.5 /bin/sh -c '"pkill -f raspiComms.py"'

sshpass -p raspberry ssh pi@192.168.88.5 /bin/sh -c '"cd /home/pi/raspi/ && python3 raspiComms.py"' &

# Restart topsides
sudo pkill -f main.py

cd ~/eer/2019/topsides/
sudo python3 main.py
