#!/usr/bin/env bash

xterm -geometry 93x31+0+0 -e gst-launch-1.0 udpsrc port=5000 ! application/x-rtp,encoding-name=H264,payload=96 ! rtph264depay ! avdec_h264 ! videoconvert ! autovideosink &
sshpass -p raspberry ssh pi@192.168.88.4 raspivid -t 0 -n -h 702 -w 1280 -fps 60 -b 3000000 -o - | gst-launch-1.0 -v fdsrc ! h264parse config-interval=1 ! rtph264pay ! udpsink host=192.168.1.20 port=5000