#!/usr/bin/env bash
# Start / Restart Script

# Open Google Chrome on localhost if it is not already running
if ps ax | grep -v grep | grep "chrome" > /dev/null
then
    echo "Google Chrome is already running."
else
    setsid google-chrome localhost &
fi

# Start / restart raspberry pi communications
sshpass -p raspberry ssh pi@192.168.88.5 /bin/sh -c '"pkill -f raspiComms.py"'
xterm -geometry 93x31+0+0 -e sshpass -p raspberry ssh pi@192.168.88.5 /bin/sh -c '"cd /home/pi/raspi/ && python3 raspiComms.py"' &

# Start / restart topsides server
sudo pkill -f main.py
cd ~/eer/2019/topsides/
sudo python3 main.py